---
version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - PORT=4000
      - BINDING=0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      # where the app is running from, see Dockerfile for the container path usage
      - ../app:/app:cached

      # where VSCode mounts the workspace, see workspaceFolder in .devcontainer/devcontainer.json
      - ..:/workspace:cached

      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - "database:/var/lib/postgresql/data"

volumes:
  database:
